package druid:ui;


interface component {
    use utils.{event, context};

    init: func(ctx: context) -> string;
    emit: func(nodeid: string, event: string, e: event);
}


world druid-ui {
    import ui;
    export component;
}
